version: '3.9'

services:
  app:
    build: .
    ports:
      - '${PORT:-3001}:3000'
    environment:
      DATABASE_URL: ${DATABASE_URL:-file:/data/local.db}
    volumes:
      - ./data:/data
    command: ["./docker-entrypoint.sh"]
